/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/backup': RouteRecordInfo<'/admin/backup', '/admin/backup', Record<never, never>, Record<never, never>>,
    '/admin/projects': RouteRecordInfo<'/admin/projects', '/admin/projects', Record<never, never>, Record<never, never>>,
    '/admin/review': RouteRecordInfo<'/admin/review', '/admin/review', Record<never, never>, Record<never, never>>,
    '/admin/students': RouteRecordInfo<'/admin/students', '/admin/students', Record<never, never>, Record<never, never>>,
    '/admin/upload': RouteRecordInfo<'/admin/upload', '/admin/upload', Record<never, never>, Record<never, never>>,
    '/admin/users': RouteRecordInfo<'/admin/users', '/admin/users', Record<never, never>, Record<never, never>>,
    '/gallery': RouteRecordInfo<'/gallery', '/gallery', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/my/': RouteRecordInfo<'/my/', '/my', Record<never, never>, Record<never, never>>,
    '/my/profile': RouteRecordInfo<'/my/profile', '/my/profile', Record<never, never>, Record<never, never>>,
    '/my/projects': RouteRecordInfo<'/my/projects', '/my/projects', Record<never, never>, Record<never, never>>,
    '/my/upload': RouteRecordInfo<'/my/upload', '/my/upload', Record<never, never>, Record<never, never>>,
    '/project/[id]': RouteRecordInfo<'/project/[id]', '/project/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/students': RouteRecordInfo<'/students', '/students', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/admin/backup.vue': {
      routes: '/admin/backup'
      views: never
    }
    'src/pages/admin/projects.vue': {
      routes: '/admin/projects'
      views: never
    }
    'src/pages/admin/review.vue': {
      routes: '/admin/review'
      views: never
    }
    'src/pages/admin/students.vue': {
      routes: '/admin/students'
      views: never
    }
    'src/pages/admin/upload.vue': {
      routes: '/admin/upload'
      views: never
    }
    'src/pages/admin/users.vue': {
      routes: '/admin/users'
      views: never
    }
    'src/pages/gallery.vue': {
      routes: '/gallery'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/my/index.vue': {
      routes: '/my/'
      views: never
    }
    'src/pages/my/profile.vue': {
      routes: '/my/profile'
      views: never
    }
    'src/pages/my/projects.vue': {
      routes: '/my/projects'
      views: never
    }
    'src/pages/my/upload.vue': {
      routes: '/my/upload'
      views: never
    }
    'src/pages/project/[id].vue': {
      routes: '/project/[id]'
      views: never
    }
    'src/pages/students.vue': {
      routes: '/students'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
